### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by Ludwiggle** [arnoudbuzing/wolfram-server#1]
On Debian 9 and Mathematica 11.3, idle CPU usage around 6%. I replaced the `TaskWait` with a `Dialog[]` to keep it alive and CPU usage dropped to 1%

**Comment by arnoudbuzing** [comment]
Thanks, this seems like a bug in `TaskWait`. I will follow up. I think `TaskWait` is the right function to use here (but it should not use that much cpu)

**Comment by arnoudbuzing** [comment]
@Ludwiggle Do you observe similar cpu usage issues with `Pause` on the same machine?

**Comment by arnoudbuzing** [comment]
I think even `Pause` uses cpu on Linux ... I think there is a bug here. The `Dialog` trick is a neat workaround, but `TaskWait` is the right function to use here, so I am going to stick with that.
