### ISSUE TITLE
python client example

### ISSUE THREAD

**Issue by arnoudbuzing** [arnoudbuzing/wolfram-server#3]
data=sys.argv[1] should probably be data=post

**Comment by kkouptsov** [comment]
Rather, these lines

https://github.com/arnoudbuzing/wolfram-server/blob/36bf70a0adc2d76ed1ce4ba6be057fda0d254458/clients/python/python-client.py#L6-L8

are not necessary. The variable `post` is not used.

**Comment by arnoudbuzing** [comment]
fixed
