### ISSUE TITLE
Parallelizing multiple servers

### ISSUE THREAD

**Issue by jcohensolal** [arnoudbuzing/wolfram-server#4]
Hello,

very useful project, thanks.

So I have a question, I am not sure how to contact you, and maybe others could be interested so I'll write this here.

I have a use case where I run this Wolfram server code on my local machine inside a notebook, and it receives requests from a Python script, it works fine, this is great. This is part of a bigger pipeline however, and the calculation I make inside my Wolfram notebook is a big bottleneck in terms of execution time.

For this reason, I'm trying to run multiple server instances simultaneously, to "load balance" the incoming requests flux. The idea is to do this by duplicating the notebook and changing the port I listen to on each notebook. 

I can currently achieve this by starting each version of the notebook on a separate instance of the Mathematica software, but by doing that, I have to use several Mathematica licenses, which severely limits the number of servers I can launch (I don't want to use too big of a proportion of the license pool available in my company).

When I'm trying to do this by using a single Mathematica instance, by just opening all the notebooks on this instance and running them, only the first one I start is effective and actually listens on the requested port, the following ones don't.

My question then is: do you see an effective way of running multiple instance of this Wolfram server code without using multiple Mathematica licenses? I'm not trying to circumvent the licensing system, I just feel like it should be possible and I am doing it wrong.

Many thanks.

**Comment by arnoudbuzing** [comment]
Those are good suggestions, but they are outside of the scope of what I intend this project to be about. Feel free to fork this repo and make these improvements!
